# fly.toml app configuration file generated for bernd on 2025-07-10T06:23:22-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bernd'
primary_region = 'den'

[build]

[[vm]]
  size = 'shared-cpu-1x'
